/* Illustrative product concept; all inputs stay local. */
const exampleMedia={0:'front',1:'back',2:'side',3:'fabric',4:'zari',5:'inside',6:'measure',7:'movement',9:'gift-closed',10:'gift-open',11:'care',12:'name-tab'};
const exampleTitle='بشت سَمت — أسود بزري ذهبي · مثال';
const cleanName=()=>$('embroidered-name').value.trim().replace(/\s+/g,' ');
const originalCategory=changeCategory;
let currentMedia='';
function conceptCaption(i){if(category!=='bisht')return plan.shots[i].caption;if(i===7)return 'صورة حركة مولّدة؛ غلاف مقترح لفيديو يُصور لاحقًا. ليست فيديو أو اختبار لبس.';if(i===6)return 'تصور لطريقة عرض القياس؛ قراءة الشريط وأرقام المثال لا تثبت مقاسًا فعليًا.';if(i===11)return 'تصور موضع ملصق العناية؛ الرموز في الصورة ليست تعليمات معتمدة للقطعة.';if(i===12)return 'مثال الاسم: أحمد العتيبي · خيط عاجي · تبويب داخلي؛ ليس نقشًا على الزري.';if(i===9||i===10)return 'تصور تغليف: صندوق + بشت + كرت. تُعتمد المشمولات والأبعاد والتكلفة قبل البيع.';return 'مثال مولّد لنفس تصور البشت؛ قطع التنسيق غير مشمولة. بيانات العارض والمقاس توضيحية أدناه.';}
showShot=function(i){shotIndex=i;const s=plan.shots[i];text('shot-title',s.name);text('shot-purpose',s.purpose);text('shot-caption',conceptCaption(i));const name=category==='bisht'?exampleMedia[i]:null;currentMedia=name?'product-examples/'+name+'.png':'';$('product-photo').hidden=!name;$('unshot').hidden=!!name;if(name){$('product-photo').src=currentMedia;$('product-photo').alt='مثال مولّد للبشت: '+s.name;}$('model-card').hidden=category!=='bisht';document.querySelectorAll('[data-shot]').forEach(b=>{b.setAttribute('aria-pressed',String(Number(b.dataset.shot)===i));const img=b.querySelector('img');if(img)img.hidden=category!=='bisht';});};
updateSummary=function(){const gift=$('gift-toggle').checked,box=$('box-toggle').checked,name=$('name-toggle').checked,adjust=$('adjust-toggle').checked;const parts=[color||'لون غير محدد',size||'مقاس غير محدد'];if(adjust)parts.push('طول نهائي: '+($('target-length').value||'لم يُحدد')+' سم');if(name)parts.push('اسم: '+(cleanName()||'لم يُكتب')+' · '+($('thread-color').value==='gold'?'خيط ذهبي':'خيط عاجي')+' · تبويب داخلي');if(gift)parts.push('هدية'+(box?' + صندوق':'')+($('gift-message').value.trim()?' + كرت برسالة':''));const summary=parts.join(' · ');text('selection-summary',summary+' · السعر الأساسي [يُعتمد] + التخصيص [يُعتمد] + الصندوق [يُعتمد] + الشحن [يحدد بالمنطقة]. المهلة الإجمالية: تجهيز + تخصيص + نقل.');text('sticky-summary',summary);$('gift-options').hidden=!gift;$('adjust-options').hidden=!adjust;$('name-options').hidden=!name;$('custom-approval').hidden=!(name||adjust);$('custom-warning').hidden=!name;text('name-preview',cleanName()||'اسمك هنا');text('name-count',$('embroidered-name').value.length+' / 24 حرفًا');document.querySelector('.name-proof').classList.toggle('gold',$('thread-color').value==='gold');filterShots();};
changeCategory=function(id){originalCategory(id);text('product-use',id==='bisht'?'حضور هادئ لمناسبتك، بتصور قصّة واسعة مفتوحة وزري ذهبي. شاهد الانسدال والتفاصيل وقارن قياسات القطعة قبل الاختيار.':'[سطر استخدام خاص بهذه الفئة، مطابق للعينة]');document.querySelector('.tag-example').hidden=id!=='bisht';$('embroidered-name').value='';$('target-length').value='';$('customer-height').value='';$('gift-message').value='';$('thread-color').value='ivory';$('approve-custom').checked=false;const first=document.querySelector('[data-color]');first.dataset.color=id==='bisht'?'أسود · مثال':'[لون 1]';first.textContent=first.dataset.color;const other=document.querySelectorAll('[data-color]')[1];other.disabled=id==='bisht';other.textContent=id==='bisht'?'لون آخر · يحتاج صوره':'[لون 2]';document.querySelectorAll('[data-size]').forEach((b,i)=>{b.dataset.size=id==='bisht'?(i===0?'M · مثال':'L · مثال'):'[مقاس '+(i+1)+']';b.textContent=b.dataset.size;});if(id==='bisht'){text('product-title',exampleTitle);text('mobile-product-title',exampleTitle);text('product-features','تصور: قصّة واسعة مفتوحة · زري ذهبي هادئ · تبويب اسم داخلي اختياري');}showShot(0);updateSummary();};
function invalidateApproval(){ $('approve-custom').checked=false;text('purchase-status','');updateSummary();}
['embroidered-name','target-length','customer-height','gift-message'].forEach(id=>$(id).addEventListener('input',invalidateApproval));['thread-color','name-toggle','adjust-toggle','gift-toggle','box-toggle'].forEach(id=>$(id).addEventListener('change',invalidateApproval));document.querySelectorAll('[data-color],[data-size]').forEach(b=>b.addEventListener('click',invalidateApproval));
$('view-gift').addEventListener('click',()=>{showShot(10);$('zoom-shot').click();});
$('zoom-shot').addEventListener('click',()=>{const img=$('zoom-image');img.hidden=!currentMedia;if(currentMedia){img.src=currentMedia;img.alt=$('product-photo').alt;}const p=document.createElement('p');p.textContent=conceptCaption(shotIndex);$('shot-dialog-body').prepend(p);});
$('simulate-add').addEventListener('click',()=>{let error='';if(!color||!size)error='اختر اللون والمقاس أولًا؛ دليل القياس بجانب المقاس.';else if($('name-toggle').checked&&(!cleanName()||cleanName().length>24||! /^[\p{L}\p{M}\s.'’\-]+$/u.test(cleanName())))error='اكتب اسمًا واضحًا حتى 24 حرفًا؛ استخدم حروفًا ومسافات دون أرقام أو رموز.';else if($('adjust-toggle').checked&&(!$('target-length').value||!$('target-length').validity.valid))error='أدخل الطول النهائي للقطعة بين 90 و160 سم للتجربة.';else if($('adjust-toggle').checked&&$('customer-height').value&&!$('customer-height').validity.valid)error='راجع طولك؛ حدود المثال 100–220 سم.';else if(($('name-toggle').checked||$('adjust-toggle').checked)&&!$('approve-custom').checked)error='راجع الاسم والطول والموضع ثم فعّل موافقة التخصيص.';text('purchase-status',error||'محاكاة ناجحة: ملخص الخيارات جاهز للمراجعة. في المتجر تتوقف الخطوة حتى اعتماد السعر والمهلة والسياسة، ثم يحفظ التدقيق مع الطلب. لا سلة أو تنفيذ خياطة فعلي هنا.');});
document.querySelectorAll('[data-shot]').forEach(b=>{const i=Number(b.dataset.shot),name=exampleMedia[i],label=b.textContent;b.replaceChildren();if(name){const img=document.createElement('img');img.src='product-examples/'+name+'.png';img.loading='lazy';img.width=1122;img.height=1402;img.alt='';b.append(img);}const span=document.createElement('span');span.textContent=i===7?'حركة · صورة غلاف':label;b.append(span);});
changeCategory('bisht');
if(location.hash==='#customization-tools')$('customization-tools').scrollIntoView();
