import {asset,productUrl,collectionUrl} from './catalog.js';
import {productOptions} from './product-options-data.js';
import {CustomizationSummary} from './ProductCustomization.jsx';
import {priceNumber,formatPrice,cartKey} from './product-utils.js';
export function PreviewCart({items,onChange,onClose}) {
 const total=items.reduce((sum,p)=>sum+priceNumber(p.price)*p.quantity,0);
 const quantity=(key,delta)=>onChange(items.map(p=>cartKey(p)===key?{...p,quantity:Math.max(1,p.quantity+delta)}:p));
 return <><h2>سلة التسوق</h2><p className="preview-note">سلة تجريبية للمعاينة، لا تُنشئ طلبًا أو حجزًا.</p>{items.length?<><ul className="preview-cart-items">{items.map((p,index)=><li key={cartKey(p)}><img src={asset('photos/collection/'+p.imageStem+'-400.webp')} alt={p.name} width="80" height="100"/><div><a href={productUrl(p.id)}>{p.name}</a><p>{p.color} · {p.size} · {p.purpose==='gift'?'هدية':'لي'}</p><CustomizationSummary options={p} category={productOptions[p.categoryKey||({bisht:'bisht',thobe:'thobe',abaya:'abaya',farwa:'farwa'}[p.id]||'bisht')]}/>{p.message&&<p className="cart-message">رسالة: {p.message}</p>}<p>{formatPrice(priceNumber(p.price)*p.quantity)} ر.س</p><div className="cart-item-actions"><button aria-label={'تقليل كمية '+p.name} disabled={p.quantity===1} onClick={()=>quantity(cartKey(p),-1)}>−</button><span aria-label="الكمية">{p.quantity}</span><button aria-label={'زيادة كمية '+p.name} onClick={()=>quantity(cartKey(p),1)}>+</button><a href={productUrl(p.id)+'?size='+encodeURIComponent(p.size)+'&edit='+index+'#product-options'}>تعديل الاختيارات</a><button className="inline-link" onClick={()=>onChange(items.filter(i=>cartKey(i)!==cartKey(p)))}>إزالة</button></div></div></li>)}</ul><div className="cart-total"><span>إجمالي القطع</span><strong>{formatPrice(total)} ر.س</strong></div><p className="option-note">إجمالي القطع فقط؛ رسوم التغليف والتخصيص والشحن غير مشمولة بعد، وتُعتمد قبل إتاحة الشراء.</p><button className="primary-button" onClick={onClose}>تابع استكشاف القطع</button></>:<><p>سلتك فارغة حاليًا. خذ وقتك في اكتشاف القطع.</p><a className="text-link" href={collectionUrl('bisht')}>اكتشف البشوت</a></>}</>;
}
